name: Deploy With SSH to Hostinger #https://github.com/Burnett01/rsync-deployments
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Hosting with rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -ravzuptP --delete --exclude .git .github
        path: ./
        remote_path: ${{ secrets.REMOTE_TARGET }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}
        remote_key_pass: ${{ secrets.REMOTE_PASSWORD }}