name: Testing Deploy With SSH

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: hengkx/ssh-deploy@v1.0.1
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
          PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: 'dist/'
          TARGET: ${{ secrets.REMOTE_TARGET }}
