name: Deployment of current GitHub repo on a server through SSH
on:
  push:
    branches: [main, develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Rxinui/ssh-deploy-repo-action@v1
        with:
          # Required
          ssh-user: ${{ secrets.REMOTE_USER }}
          ssh-password: ${{ secrets.REMOTE_PASSWORD }}
          ssh-domain: ${{ secrets.REMOTE_HOST }}
          # Optional          
          target-branch: main
          target-directory: ${{ secrets.REMOTE_TARGET }}